[package]
name = "jailer"
version = "1.16.0-dev"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2024"
description = "Process for starting Firecracker in production scenarios; applies a cgroup/namespace isolation barrier and then drops privileges."
homepage = "https://firecracker-microvm.github.io/"
license = "Apache-2.0"

[lib]
name = "jailer"
path = "src/lib.rs"

[[bin]]
name = "jailer"
path = "src/bin/jailer.rs"
bench = false

[[bin]]
name = "landlock-jailer"
path = "src/bin/landlock_jailer.rs"
bench = false

[[bin]]
name = "setup-bench"
path = "src/bin/setup_bench.rs"
bench = false


[features]
tracing = ["log-instrument", "utils/tracing"]

[dependencies]
libc = "0.2.186"
landlock = "0.4.5"
log-instrument = { path = "../log-instrument", optional = true }
regex = { version = "1.12.3", default-features = false, features = ["std"] }
thiserror = "2.0.18"
vmm-sys-util = "0.15.0"

utils = { path = "../utils" }

[lints]
workspace = true
